//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class bankaccount
    {
        public int IdBankAccount { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual customer customer { get; set; }
    }
}
