//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class customersocialtype
    {
        public int IdCustomerSocialType { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<int> IdSocialType { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual socialtype socialtype { get; set; }
    }
}
