//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class customersocialtype
    {
        public int IdCustomerSocialType { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<int> IdSocialType { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual socialtype socialtype { get; set; }
    }
}
