//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class servicesocialtype
    {
        public int IdServiceSocialType { get; set; }
        public Nullable<int> ServiceIdSocialtype { get; set; }
        public Nullable<int> SocialTypeId { get; set; }
    
        public virtual service service { get; set; }
        public virtual socialtype socialtype { get; set; }
    }
}
