//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class servicesocialtype
    {
        public int IdServiceSocialType { get; set; }
        public Nullable<int> ServiceIdSocialtype { get; set; }
        public Nullable<int> SocialTypeId { get; set; }
    
        public virtual service service { get; set; }
        public virtual socialtype socialtype { get; set; }
    }
}
