//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class serviceexecution
    {
        public int IdServiceExecution { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ServiceIdServiceExecution { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<sbyte> PayOrFree { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual service service { get; set; }
    }
}
