//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class soccenEntities : DbContext
    {
        public soccenEntities()
            : base("name=soccenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<bankaccount> bankaccounts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customersocialtype> customersocialtypes { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<serviceexecution> serviceexecutions { get; set; }
        public virtual DbSet<servicesocialtype> servicesocialtypes { get; set; }
        public virtual DbSet<socialtype> socialtypes { get; set; }
        public virtual DbSet<street> streets { get; set; }
    }
}
