//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class soccenEntities : DbContext
    {
        public soccenEntities()
            : base("name=soccenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customersocialtype> customersocialtypes { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<serviceexecution> serviceexecutions { get; set; }
        public virtual DbSet<servicesocialtype> servicesocialtypes { get; set; }
        public virtual DbSet<socialtype> socialtypes { get; set; }
        public virtual DbSet<street> streets { get; set; }
    }
}
